language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python main.py
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - "docs/index.md"
  skip_cleanup: true
  on:
    tags: true
